### ISSUE TITLE
background color Entry widget 8.6.11

### ISSUE THREAD

**Issue by ghost** [chrstphrchvz/perl-tcl-ptk#21]
With the latest Tcl/Tk 8.6.11 on macOS (tested Mojave and bigSur) the background color of a Entry widget without focus has a wrong color (gray instead of white). Tcl/Tk code in Wish does not present this issue (see screenshot)

PS: this does not happen with 8.6.10

![Screenshot 2021-02-20 at 18 52 26](https://user-images.githubusercontent.com/66279560/108604260-20b1ed00-73ad-11eb-9342-b6fd644be154.png)

**Comment by chrstphrchvz** [comment]
I believe this is a regression in Tcl/Tk 8.6.11. I notice that as of tcltk/tk@e7be12248b the Ttk entry widget by default has gray rather than white background under Aqua light mode (regardless of focus). Reported upstream: https://core.tcl-lang.org/tk/info/58222c42b37d57f3

**Comment by chrstphrchvz** [comment]
This should be fixed in Tcl/Tk 8.6.12.
