### ISSUE TITLE
Request about support of ttk::labelframe

### ISSUE THREAD

**Issue by ghost** [chrstphrchvz/perl-tcl-ptk#31]
Is the widget ttk::labelframe (as in https://www.tcl.tk/man/tcl/TkCmd/ttk_labelframe.html) supported by this framework? I can have the LabFrame widget working but not the ttk variant. Thanks

What I do now is a cumbersome way through TCL:

````
    my $int = $mw->interp;
    my $labelFramePATH = $int->widget($FrameSettingsView);
    my $Widgetname = $labelFramePATH . '.lf01';
    $int->Eval("
        ttk::labelframe $Widgetname -text INTERFACE -relief ridge -height 100 -width 100
            pack $Widgetname -expand true -fill x
    ");
    my $labelFrame = $int->widget($Widgetname);
````

**Comment by chrstphrchvz** [comment]
Yes: `$widget->ttkLabelframe(…)`

There are examples in the tileWidget.t test and in some widget demos: https://github.com/search?q=repo%3Achrstphrchvz%2Fperl-tcl-ptk%20ttkLabelframe&type=code

**Comment by ghost** [comment]
Thanks. Not sure how I could miss it. Works fine.
